name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            accept-flake-config = true
      - uses: DeterminateSystems/magic-nix-cache-action@v1
      - run: nix build -L
