on: [push]
jobs:
  ci:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amesgen/actions/setup@win-ghc-9.0.1-test
        with:
          ghc-version: 9.0.1
      - run: cabal build
