name: "Test"
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - "884"
          - "8104"
          - "901"
    steps:
    - uses: actions/checkout@v2
      with:
        repository: tweag/ormolu
        ref: ghc-9.0
    - uses: cachix/install-nix-action@v13
    - run: nix-build --keep-going --no-out-link --argstr ormoluCompiler ghc${{ matrix.ghc }}
