name: Test
on:
  push:
jobs:
  test:
    runs-on: windows-latest
    steps:
      - shell: bash
        run: |
          curl -sL https://github.com/amesgen/ormolu/releases/download/test-macos-4/ormolu-Windows.zip > ormolu-Windows.zip
          7z e ormolu-Windows.zip

          echo RUNNING
          ./ormolu --version
